### ISSUE TITLE
Great now need automations and switches!

### ISSUE THREAD

**Issue by mzac** [Lopton/hassUnifiBlockSwitch#1]
I just set this up for the iPad and iPod, now I need to figure out how to write automations and other switches to trigger depending on who is using the device.  When I'm done I could share some examples here and you could include it in your README if you'd like?

**Comment by Matt-PMCT** [comment]
Sure that would be great

**Comment by Matt-PMCT** [comment]
I'm no longer supporting this since the functionality is now in base Home Assistant. Closing all issues, archiving the project
