### ISSUE TITLE
Support for custom_updater 

### ISSUE THREAD

**Issue by johntdyer** [Lopton/hassUnifiBlockSwitch#2]
You should publish the Json in the repo for custom updater.

**Comment by Chaotic** [comment]
custom_updater has been deprecated and replaced with HACS.  https://github.com/custom-components/hacs

Would still be a good edition.

**Comment by Matt-PMCT** [comment]
I'm no longer supporting this since the functionality is now in base Home Assistant. Closing all issues, archiving the project
