### ISSUE TITLE
HA 0.92 has new custom component changes

### ISSUE THREAD

**Issue by joshsinykin** [Lopton/hassUnifiBlockSwitch#3]
a manifest file and _init_.py are needed to get this component to work. I hacked one together to get the component to load. 

Details found here:
https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html

Custom_updater is nice feature as well.

ps. I use this component every night to shut my kids off the internet at the end of show time. They get the message when their youtube videos stop streaming and mom and dad dont need to yell at them to. So, big thanks to this component. If you need motivation to keep this up, I am sure I am not the only one who would pitch in for some coffee money.

**Comment by Matt-PMCT** [comment]
Thanks for the very helpful issue with the link. I have updated it and tested it my local setup, this brings this component back, please note the configuration has changed slightly!
