### ISSUE TITLE
pyunifi changed to aiounifi

### ISSUE THREAD

**Issue by goncalvespedro** [Lopton/hassUnifiBlockSwitch#5]
Hi

Thanks for a fantastic component,

I have updated to Home Assistant to 0.95 and it seems to have stopped broken the component. 

As part of the new Home Assistant update to 0.95 there is as part of the change that changed pyunifi to aiounifi, so i'm wondering if this could have broken something as you reference pyunifi.

Home Assistant 0.95 (Changes)
"Replace pyunifi with aiounifi in UniFi device tracker (@Kane610 - #24149) (unifi docs)"
"UniFi simplify update (@Kane610 - #24304) (unifi docs)"

https://www.home-assistant.io/blog/2019/06/26/release-95/

Thanks in advance

**Comment by goncalvespedro** [comment]
Strange I must have rebooted a lot and removed some cached info and it's now working, not too sure what happened maybe pyunifi is still there :)

**Comment by Matt-PMCT** [comment]
Looking in to this, but will be a bit, glad to hear its work in the short term

**Comment by Kane610** [comment]
I will add this functionality native further down the line. Im migrating unifi device tracker to config entry and then a few bugs then this

**Comment by Matt-PMCT** [comment]
@Kane610 That will be great, let me know if I can help you out at all

**Comment by Kane610** [comment]
Much appreciated @Lopton

**Comment by Kane610** [comment]
PR for hass is up https://github.com/home-assistant/home-assistant/pull/25478

Just need to add tests

**Comment by Matt-PMCT** [comment]
I'm no longer supporting this since the functionality is now in base Home Assistant. Closing all issues, archiving the project
